name: update-stats
on:
  schedule:
    - cron: '5/30 * * * *'
jobs:
  download-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download and process stats
        run: |
          curl https://raw.githubusercontent.com/joplin/plugins/refs/heads/master/stats.json | jq '([."com.ckant.joplin-plugin-better-code-blocks"[].downloadCount ] | add | {"com.ckant.joplin-plugin-better-code-blocks": .}) * ([."com.ckant.joplin-plugin-editor-themes"[].downloadCount ] | add | {"com.ckant.joplin-plugin-editor-themes": .} )' > downloads.json
        working-directory: ${{ github.workspace }}
      - name: Commit and push downloads
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add downloads.json
          if ! [ -z "$(git status --porcelain)" ]; then 
            git commit -m 'Update downloads'
            git push
          fi
